FROM python:3.12-slim

# ENV PIP_NO_CACHE_DIR=1 \
#     PYTHONDONTWRITEBYTECODE=1 \
#     PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends 
# \
#     build-essential git ffmpeg libgl1 libsm6 libxext6 \
#   && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python"]