FROM python:3.12-slim

# ENV PIP_NO_CACHE_DIR=1 \
#     PYTHONDONTWRITEBYTECODE=1 \
#     PYTHONUNBUFFERED=1

# Install runtime libraries required by OpenCV and media processing
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	   libgl1 \
	   libglib2.0-0 \
	   libsm6 \
	   libxext6 \
	   libxrender1 \
	   ffmpeg \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python"]