name: Run linter

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: |
          npm run lint